### ISSUE TITLE
No TEMPLATE branch

### ISSUE THREAD

**Issue by ewels** [nf-core/kmermaid#92]
Hello!

I just pushed a new release of nf-core/tools with the template, but kmermaid failed to sync because it doesn't have a `TEMPLATE` branch (see https://github.com/nf-core/tools/issues/709#issuecomment-666683931).

Normally this branch is created when the pipeline repo is "vanilla" with no modifications from the nf-core/tools template. The `TEMPLATE` branch needs to have a common history with a commit in the main branch which has this state.

It looks like this pipeline wasn't created with `nf-core create`, so this is a little trickier. The pipeline has to have a manual merge. This process is described in https://nf-co.re/developers/sync#manual-synchronisation

Once you've done this once, all future automated PRs should work fine.

Shout if you have any problems!

Phil

**Comment by pranathivemuri** [comment]
https://github.com/nf-core/kmermaid/tree/TEMPLATE - Olga and I made a branch now

**Comment by ewels** [comment]
Ok nice! However I'm afraid that this isn't resolved yet - just creating an orphan `TEMPLATE` branch is not enough. You need to go on to do the merge into your main code branches (i.e. `dev`) with the `--allow-unrelated-histories` as described here: https://nf-co.re/developers/sync#merge-template-into-main-branches

Currently the `TEMPLATE` branch doesn't [share any git history](https://github.com/nf-core/kmermaid/compare/TEMPLATE) with `dev`, so no pull-requests or automation can use it:

<img src="https://user-images.githubusercontent.com/465550/96689593-e8f55300-1382-11eb-9865-8e38f87ebf32.png" width=500>

Once you have done one merge as described in the docs above, they will have shared history and everything will (should) work smoothly from that point onwards.

I hope this makes sense, shout if you have any questions.

Phil

**Comment by pranathivemuri** [comment]
https://github.com/nf-core/kmermaid/pull/110 - Thanks for the feedback, please let us know if this PR will make the sync automatic from next time!
